Repository CDS-Mobile1/CDS-Instagram-Android, pull requests merged in 2023-05, with the labels that each got.

#11 [CHORE/#10] pr builder 오류 해결
  app/src/androidTest/java/com/sopt/instagram/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/instagram/di/RetrofitModule.kt
  app/src/test/java/com/sopt/instagram/ExampleUnitTest.kt
Labels: CHORE 🎀, PULL REQUEST 🚀, 채연 😼

#8 [UI/#6] newpost/newpost 기본적인 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/instagram/data/model/response/GetPostResponseDto.kt
  app/src/main/java/com/sopt/instagram/ui/home/HomeFragment.kt
  app/src/main/java/com/sopt/instagram/ui/home/HomeViewModel.kt
  app/src/main/java/com/sopt/instagram/ui/home/PostAdapter.kt
  app/src/main/java/com/sopt/instagram/ui/home/PostImagesAdapter.kt
  app/src/main/java/com/sopt/instagram/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/instagram/ui/newpost/ItemTouchCallback.kt
  app/src/main/java/com/sopt/instagram/ui/newpost/ItemTouchHelperListener.kt
  app/src/main/java/com/sopt/instagram/ui/newpost/NewPostActivity.kt
  app/src/main/java/com/sopt/instagram/ui/newpost/NewPostImageAdapter.kt
  app/src/main/java/com/sopt/instagram/util/binding/BindingFragment.kt
  app/src/main/res/drawable/ic_home_comment.xml
  app/src/main/res/drawable/ic_home_dm.xml
  app/src/main/res/drawable/ic_home_like.xml
  app/src/main/res/drawable/ic_home_more.xml
  app/src/main/res/drawable/ic_home_save.xml
  app/src/main/res/drawable/ic_home_title.xml
  app/src/main/res/drawable/ic_home_under_arrow.xml
  app/src/main/res/drawable/ic_menu_home.xml
  app/src/main/res/drawable/ic_menu_mypage.xml
  app/src/main/res/drawable/ic_menu_new_post.xml
  app/src/main/res/drawable/ic_menu_reels.xml
  app/src/main/res/drawable/ic_menu_search.xml
  app/src/main/res/drawable/ic_newpost_check.xml
  app/src/main/res/drawable/ic_newpost_location.xml
  app/src/main/res/drawable/ic_newpost_setting.xml
  app/src/main/res/drawable/ic_newpost_share.xml
  app/src/main/res/drawable/ic_newpost_user.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_new_post.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_newpost_image.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/item_post_image.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/menu/menu_main_toolbar.xml
  app/src/main/res/menu/menu_newpost_toolbar.xml
  app/src/main/res/values/Styles.xml
  app/src/main/res/values/strings.xml
Labels: UI 💐, 선환 🦝

#9 [UI/#5] Dm / UI 기본 구현
  app/build.gradle
  app/src/androidTest/java/com/sopt/instagram/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/instagram/data/ApiFactory.kt
  app/src/main/java/com/sopt/instagram/data/model/request/DmstarredRequestDto.kt
  app/src/main/java/com/sopt/instagram/data/model/response/DmstoryResponseDto.kt
  app/src/main/java/com/sopt/instagram/data/service/DmstarredService.kt
  app/src/main/java/com/sopt/instagram/data/service/DmstoryService.kt
  app/src/main/java/com/sopt/instagram/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/instagram/ui/main/dm/DmActivity.kt
  app/src/main/java/com/sopt/instagram/ui/main/dm/GetStoryAdapter.kt
  app/src/main/res/drawable/btn_dm_star.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_dm_star_press.xml
  app/src/main/res/drawable/ic_dm_star_unpress.xml
  app/src/main/res/drawable/ic_newdm.xml
  app/src/main/res/drawable/ic_vector.xml
  app/src/main/res/drawable/img_dm_search.xml
  app/src/main/res/layout/activity_dm.xml
  app/src/main/res/layout/item_dm_message.xml
  app/src/main/res/layout/item_dm_starred.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/sopt/instagram/ExampleUnitTest.kt
Labels: UI 💐, 민주 🦉

#14 [UI/#3] story / story UI 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/instagram/di/RetrofitModule.kt
  app/src/main/java/com/sopt/instagram/domain/entity/Member.kt
  app/src/main/java/com/sopt/instagram/domain/entity/Story.kt
  app/src/main/java/com/sopt/instagram/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/instagram/ui/story/CubeOutRotationTransformer.kt
  app/src/main/java/com/sopt/instagram/ui/story/StoryActivity.kt
  app/src/main/java/com/sopt/instagram/ui/story/StoryAdapter.kt
  app/src/main/java/com/sopt/instagram/ui/story/StoryUiState.kt
  app/src/main/java/com/sopt/instagram/ui/story/StoryViewModel.kt
  app/src/main/java/com/sopt/instagram/ui/story/member/MemberStoryFragment.kt
  app/src/main/java/com/sopt/instagram/ui/story/member/MemberStoryUiState.kt
  app/src/main/java/com/sopt/instagram/ui/story/member/MemberStoryViewModel.kt
  app/src/main/java/com/sopt/instagram/ui/story/tag/TagDialogFragment.kt
  app/src/main/java/com/sopt/instagram/util/binding/BindingAdapter.kt
  app/src/main/java/com/sopt/instagram/util/binding/BindingBottomSheetDialog.kt
  app/src/main/java/com/sopt/instagram/util/extension/IntegerExt.kt
  app/src/main/res/drawable/ic_story_detail.xml
  app/src/main/res/drawable/ic_story_like.xml
  app/src/main/res/drawable/ic_story_send.xml
  app/src/main/res/drawable/ic_story_tag.xml
  app/src/main/res/drawable/shape_blue_fill_8_rect.xml
  app/src/main/res/drawable/shape_gray2_fill_1000_rect.xml
  app/src/main/res/drawable/shape_gray3_fill_6_rect.xml
  app/src/main/res/drawable/shape_gray3_fill_oval.xml
  app/src/main/res/drawable/shape_gray5_fill_1000_rect.xml
  app/src/main/res/drawable/shape_gray5_line_24_rect.xml
  app/src/main/res/drawable/shape_white_fill_oval.xml
  app/src/main/res/layout/activity_story.xml
  app/src/main/res/layout/fragment_member_story.xml
  app/src/main/res/layout/fragment_tag_dialog.xml
  app/src/main/res/layout/item_tag_member.xml
  app/src/main/res/layout/view_story_progress_bar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: PULL REQUEST 🚀, UI 💐, 채연 😼

#16 [FEAT/#15] story / story 서버 통신
  app/src/main/java/com/sopt/instagram/data/model/response/GetMemberStoryResponseDto.kt
  app/src/main/java/com/sopt/instagram/data/model/response/GetTaggedMemberResponseDto.kt
  app/src/main/java/com/sopt/instagram/data/repository/StoryRepositoryImpl.kt
  app/src/main/java/com/sopt/instagram/data/service/StoryService.kt
  app/src/main/java/com/sopt/instagram/data/source/StoryDataSource.kt
  app/src/main/java/com/sopt/instagram/di/RepositoryModule.kt
  app/src/main/java/com/sopt/instagram/di/ServiceModule.kt
  app/src/main/java/com/sopt/instagram/domain/entity/Tag.kt
  app/src/main/java/com/sopt/instagram/domain/repository/StoryRepository.kt
  app/src/main/java/com/sopt/instagram/ui/story/StoryActivity.kt
  app/src/main/java/com/sopt/instagram/ui/story/StoryViewModel.kt
  app/src/main/java/com/sopt/instagram/ui/story/member/MemberStoryFragment.kt
  app/src/main/java/com/sopt/instagram/ui/story/member/MemberStoryUiState.kt
  app/src/main/java/com/sopt/instagram/ui/story/member/MemberStoryViewModel.kt
  app/src/main/java/com/sopt/instagram/ui/story/tag/TagAdapter.kt
  app/src/main/java/com/sopt/instagram/ui/story/tag/TagDialogFragment.kt
  app/src/main/java/com/sopt/instagram/ui/story/tag/TagViewModel.kt
  app/src/main/res/layout/fragment_tag_dialog.xml
  app/src/main/res/layout/item_tag_member.xml
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 😼

#21 [Feat/#20] newpost / api 연결
  app/src/main/java/com/sopt/instagram/data/model/request/NewPostRequestDto.kt
  app/src/main/java/com/sopt/instagram/data/model/response/NewPostResponseDto.kt
  app/src/main/java/com/sopt/instagram/data/repository/PostNewPostRepositoryImpl.kt
  app/src/main/java/com/sopt/instagram/data/service/PostNewPostService.kt
  app/src/main/java/com/sopt/instagram/data/source/PostNewPostSource.kt
  app/src/main/java/com/sopt/instagram/di/RepositoryModule.kt
  app/src/main/java/com/sopt/instagram/di/ServiceModule.kt
  app/src/main/java/com/sopt/instagram/domain/entity/NewPost.kt
  app/src/main/java/com/sopt/instagram/domain/repository/PostNewPostRepository.kt
  app/src/main/java/com/sopt/instagram/ui/newpost/NewPostActivity.kt
  app/src/main/java/com/sopt/instagram/ui/newpost/NewPostViewModel.kt
  app/src/main/res/layout/activity_new_post.xml
Labels: FEAT ✨, 선환 🦝

#22 [Feat/#6] newpost / dialog 구현
  app/src/main/java/com/sopt/instagram/ui/newpost/BackButtonDialog.kt
  app/src/main/java/com/sopt/instagram/ui/newpost/NewPostActivity.kt
  app/src/main/java/com/sopt/instagram/util/binding/BindingDialog.kt
  app/src/main/res/drawable/shape_white_fill_radius_20dp.xml
  app/src/main/res/layout/fragment_newpost_dialog.xml
Labels: FEAT ✨, 선환 🦝

#26 [DOCS] 데모 영상 변경 및 패키지 컨벤션 노션 링크 추가
  README.md
Labels: CHORE 🎀, PULL REQUEST 🚀, 채연 😼
